cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/


stages:
  - setup
  - deploy

setup:
  stage: setup
  tags: [arigato]
  script:
  - yarn

deploy:
  stage: deploy
  tags: [arigato]
  script:
    - yarn build
    - rm -rf "${WWW_ROOT}/holo/"
    - cp -R build "${WWW_ROOT}/holo/"
    - cp index.html "${WWW_ROOT}/holo/"
